azs:
- name: z1
  cloud_properties:
    zone: asia-east1-a
- name: z2
  cloud_properties:
    zone: asia-east1-b
- name: z3
  cloud_properties:
    zone: asia-east1-c

vm_types:
- name: default
  cloud_properties:
    machine_type: n1-standard-1
    root_disk_size_gb: 20
    root_disk_type: pd-standard
- name: large
  cloud_properties:
    machine_type: n1-standard-2
    root_disk_size_gb: 50
    root_disk_type: pd-standard

disk_types:
- name: default
  disk_size: 3000
- name: large
  disk_size: 50_000

networks:
- name: vpc-ci
  type: manual
  subnets:
  - range: 192.168.1.0/24
    gateway: 192.168.1.1
    azs: [z1, z2, z3]
    dns: [8.8.8.8]
    cloud_properties:
      network_name: vpc-ci
      subnetwork_name: ci-infra
      ephemeral_external_ip: true
      tags: [internal,concourse,bosh-ext]
- name: vip
  type: vip

compilation:
  workers: 3
  reuse_compilation_vms: true
  az: z1
  vm_type: default
  network: vpc-ci
